dist: trusty

compiler:
    - gcc

os:
    - linux

before_script:
    ./autogen.sh

language: c

addons:
    apt:
        sources:
            - ubuntu-toolchain-r-test
        packages:
            - libglib2.0-dev
            - libcurl4-gnutls-dev
            - valgrind
            - autoconf 
            - automake
            - check
            - libelf-dev
            - libdw-dev

install:
        - wget http://downloads.sourceforge.net/project/check/check/0.10.0/check-0.10.0.tar.gz
        - tar -xvf check-0.10.0.tar.gz
        - pushd check-0.10.0 && ./configure --prefix=/usr --libdir=/usr/lib/x86_64-linux-gnu && make -j48 && sudo make install && popd

script:
    - ./configure && make && make check

after_failure: cat test-suite.log
